import React, { useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronRight, Globe2, Mail, MapPin, Menu, Phone, Plane, Search, Send, ShieldCheck, Sparkles, Users, X } from 'lucide-react';

const destinations=[
 {name:'Bali',country:'Indonesia',tag:'Island escape',image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=85'},
 {name:'Santorini',country:'Greece',tag:'Mediterranean',image:'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=85'},
 {name:'Jaipur',country:'India',tag:'Royal heritage',image:'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=85'},
 {name:'Kyoto',country:'Japan',tag:'Culture & calm',image:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=85'},
 {name:'Swiss Alps',country:'Switzerland',tag:'Mountain retreat',image:'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=85'},
 {name:'Amalfi Coast',country:'Italy',tag:'Coastal beauty',image:'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=900&q=85'}
];
const packages=[
 {title:'Bali Discovery',place:'Indonesia',days:'6 days / 5 nights',price:'₹42,999',image:destinations[0].image,items:['Hotels & breakfast','Airport transfers','Island day tour']},
 {title:'Royal Rajasthan',place:'India',days:'5 days / 4 nights',price:'₹28,499',image:destinations[2].image,items:['Heritage stays','Private transfers','Local guide']},
 {title:'Greek Getaway',place:'Greece',days:'7 days / 6 nights',price:'₹68,999',image:destinations[1].image,items:['Boutique stays','Island cruise','Breakfast daily']}
];
const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
function Navbar(){const [open,setOpen]=useState(false);return <header className="navbar"><div className="container nav"><button className="brand" onClick={()=>go('home')}><span className="brandmark"><Plane size={19}/></span>Wanderly</button><nav className={open?'navlinks open':'navlinks'}>{[['Home','home'],['Destinations','destinations'],['Packages','packages'],['About','about'],['Contact','contact']].map(([x,id])=><button key={id} onClick={()=>{go(id);setOpen(false)}}>{x}</button>)}<button className="navcta" onClick={()=>{go('booking');setOpen(false)}}>Book a Trip</button></nav><button className="menubtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Hero({query,setQuery}){return <section id="home" className="hero"><div className="herooverlay"/><div className="container heroin"><span className="eyebrow"><Sparkles size={15}/> Curated journeys, unforgettable memories</span><h1>Travel beyond <em>ordinary.</em></h1><p>Discover inspiring places, handpicked experiences and thoughtfully designed trips for your next adventure.</p><form className="searchbox" onSubmit={e=>{e.preventDefault();go('destinations')}}><MapPin/><div><label>Where to?</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a destination"/></div><button className="primary" type="submit"><Search size={17}/> Explore</button></form><div className="stats"><span><b>120+</b> destinations</span><span><b>4.9/5</b> traveler rating</span><span><b>24/7</b> trip support</span></div></div></section>}
function Destinations({query,book}){const list=destinations.filter(d=>(d.name+' '+d.country).toLowerCase().includes(query.toLowerCase()));return <section id="destinations" className="section soft"><div className="container"><div className="sectionhead"><div><small>WANDERLUST STARTS HERE</small><h2>Popular destinations</h2></div><p>From peaceful escapes to vibrant cities, find a place that feels made for you.</p></div><div className="destgrid">{list.map(d=><article className="dest" key={d.name}><img src={d.image} alt={d.name}/><div className="destinfo"><small>{d.tag}</small><h3>{d.name}</h3><p><MapPin size={14}/> {d.country}</p><button onClick={()=>book(d.name)}><ArrowRight/></button></div></article>)}</div>{!list.length&&<div className="empty">No destinations found. Try Bali, Jaipur or Kyoto.</div>}</div></section>}
function Packages({book}){return <section id="packages" className="section"><div className="container"><div className="sectionhead"><div><small>MADE FOR YOU</small><h2>Signature tour packages</h2></div><p>Simple, transparent packages with the essentials covered.</p></div><div className="packgrid">{packages.map(p=><article className="pack" key={p.title}><img src={p.image} alt={p.title}/><div><div className="packtop"><span>{p.place}</span><b>{p.price}</b></div><h3>{p.title}</h3><p className="muted"><CalendarDays size={15}/> {p.days}</p><ul>{p.items.map(i=><li key={i}><Check size={15}/> {i}</li>)}</ul><button className="textbtn" onClick={()=>book(p.place)}>Plan this trip <ChevronRight size={16}/></button></div></article>)}</div></div></section>}
function Booking({selected}){const [sent,setSent]=useState(false);const [form,setForm]=useState({destination:selected||'',name:'',email:'',date:'',travelers:'2'});React.useEffect(()=>setForm(f=>({...f,destination:selected||f.destination})),[selected]);const upd=e=>setForm({...form,[e.target.name]:e.target.value});return <section id="booking" className="booking"><div className="container bookinggrid"><div><small>YOUR NEXT CHAPTER</small><h2>Let’s plan something unforgettable.</h2><p>Tell us a little about your trip. This portfolio booking flow demonstrates React state, forms and responsive UI.</p><div className="contactmini"><span><MapPin/> New Delhi · Mumbai · Bengaluru</span><span><Mail/> hello@wanderly.example</span><span><Phone/> +91 00000 00000</span></div></div><div className="formcard">{sent?<div className="success"><Check size={48}/><h3>Request received!</h3><p>Thanks, {form.name||'traveler'}. Your request for {form.destination||'your destination'} is ready.</p><button className="primary" onClick={()=>setSent(false)}>Send another</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="formgrid"><label>Destination<input required name="destination" value={form.destination} onChange={upd} placeholder="e.g. Bali"/></label><label>Travel date<input required type="date" name="date" value={form.date} onChange={upd}/></label><label>Your name<input required name="name" value={form.name} onChange={upd} placeholder="Full name"/></label><label>Travelers<select name="travelers" value={form.travelers} onChange={upd}>{['1','2','3','4','5+'].map(n=><option key={n}>{n}</option>)}</select></label><label className="full">Email<input required type="email" name="email" value={form.email} onChange={upd} placeholder="you@example.com"/></label></div><button className="primary fullbtn" type="submit"><Send size={17}/> Request itinerary</button></form>}</div></div></section>}
function About(){return <section id="about" className="section"><div className="container aboutgrid"><img className="aboutimg" src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85" alt="Traveler enjoying a scenic landscape"/><div><small>ABOUT WANDERLY</small><h2>Travel should feel personal, not complicated.</h2><p className="muted">Wanderly is a portfolio travel platform concept focused on making trip discovery inspiring and booking effortless.</p><p className="muted">We bring destinations, experiences and practical planning into one calm, responsive interface.</p><div className="values"><div><Globe2/><span><b>Curated globally</b><small>Handpicked destinations and experiences.</small></span></div><div><ShieldCheck/><span><b>Thoughtful planning</b><small>Clear details with no confusing steps.</small></span></div><div><Users/><span><b>Made for travelers</b><small>A friendly experience on every screen.</small></span></div></div></div></div></section>}
function Contact(){const [sent,setSent]=useState(false);return <section id="contact" className="section soft"><div className="container contactgrid"><div><small>GET IN TOUCH</small><h2>Questions before you go?</h2><p className="muted">We’re here to help with destination ideas, package details and trip planning.</p><div className="contactlist"><span><MapPin/> 12 Travel Avenue, New Delhi</span><span><Mail/> hello@wanderly.example</span><span><Phone/> +91 00000 00000</span></div></div><form className="contactform" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent&&<div className="notice">Thanks! Your message was recorded in this demo.</div>}<label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Message<textarea required rows="5" placeholder="How can we help?"/></label><button className="primary" type="submit"><Send size={17}/> Send message</button></form></div></section>}
function Footer(){return <footer><div className="container footergrid"><div><button className="brand footerbrand" onClick={()=>go('home')}><span className="brandmark"><Plane size={18}/></span>Wanderly</button><p>Modern travel discovery for curious people and meaningful journeys.</p></div><div><h4>Explore</h4><button onClick={()=>go('destinations')}>Destinations</button><button onClick={()=>go('packages')}>Tour packages</button><button onClick={()=>go('booking')}>Booking</button></div><div><h4>Company</h4><button onClick={()=>go('about')}>About us</button><button onClick={()=>go('contact')}>Contact</button></div><div><h4>Contact</h4><p><MapPin size={15}/> New Delhi, India</p><p><Mail size={15}/> hello@wanderly.example</p></div></div><div className="container footbottom">© 2026 Wanderly · Frontend portfolio project</div></footer>}
export default function App(){const [query,setQuery]=useState('');const [selected,setSelected]=useState('');const book=d=>{setSelected(d);setTimeout(()=>go('booking'),0)};return <><Navbar/><main><Hero query={query} setQuery={setQuery}/><Destinations query={query} book={book}/><Packages book={book}/><Booking selected={selected}/><About/><Contact/></main><Footer/></>}
